global:
  scrape_interval: 2s

scrape_configs:
  - job_name: sensor-service
    static_configs:
      - targets: ["localhost:8001"]
  - job_name: actuator-service
    static_configs:
      - targets: ["localhost:8002"]
  - job_name: controller-service
    static_configs:
      - targets: ["localhost:8003"]
  - job_name: telemetry-service
    static_configs:
      - targets: ["localhost:8004"]
